# Generated by Django 4.2.7 on 2024-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirm_email',
            field=models.BooleanField(default=False, verbose_name='Подтверждение email'),
        ),
    ]
