# Generated by Django 4.2.7 on 2024-05-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0003_customuser_saved_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_key',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Ключ подтверждения email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='saved_statistic',
            field=models.JSONField(default=dict),
        ),
    ]
