# Generated by Django 4.2.7 on 2024-05-26 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='league_images/', verbose_name='Фото лиги')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя игрока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='player_images/', verbose_name='Фото игрока')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubles', models.BooleanField(default=False, verbose_name='Пара')),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_player1', to='parserTableTennis.player', verbose_name='Игрок 1')),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_player2', to='parserTableTennis.player', verbose_name='Игрок 2')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('odds', models.JSONField(default=dict, verbose_name='Коэффициенты')),
                ('result', models.JSONField(default=dict, verbose_name='Результат')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='parserTableTennis.league', verbose_name='Лига')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team1', to='parserTableTennis.team', verbose_name='Команда 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_team2', to='parserTableTennis.team', verbose_name='Команда 2')),
            ],
        ),
    ]
